# Generated by Django 5.0.7 on 2024-07-22 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Марка')),
                ('model', models.CharField(max_length=32, verbose_name='Модель')),
                ('type', models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбэк'), ('pickup_truck', 'Пикап'), ('suv', 'Внедорожник'), ('cargo', 'Грузовик'), ('bus', 'Автобус')], max_length=32, verbose_name='Тип кузова')),
                ('tank_capacity', models.FloatField(verbose_name='Объем бака')),
                ('weight', models.IntegerField(verbose_name='Масса')),
                ('number_of_seats', models.IntegerField(verbose_name='Количество мест')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='Номер')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('year_of_manufacture', models.CharField(max_length=4, verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
